### ISSUE TITLE
Error en el comando avisar al usar NOMD

### ISSUE THREAD

**Issue by holasoyender** [Discusss/la-cabra#2]
Cuando avisas a un usuario con la cabra premium y el argumento `NOMD` lo ignora y envía el mensaje al MD del usuario de todas formas.

# Pasos a reproducir
Poner el comando `<prefijo>avisar <ID> NOMD [Nota] Aviso`

# Pruebas
 
![image](https://user-images.githubusercontent.com/63854611/186502190-954c2473-08d2-4592-91bd-ce3c9d6bc8b7.png)

# Frustración de los usuarios

![image](https://user-images.githubusercontent.com/63854611/186502272-69a4512f-b072-4927-98b0-d173c69e9092.png)

**Comment by holasoyender** [comment]
Servidor en el que ha ocurrido el error: `910907192989843548`

**Comment by holasoyender** [comment]
Un volcán (del nombre del dios mitológico romano [Vulcano](https://es.wikipedia.org/wiki/Vulcano_(mitolog%C3%ADa))) es una estructura geológica por la que emerge el [magma](https://es.wikipedia.org/wiki/Magma) que se divide en [lava](https://es.wikipedia.org/wiki/Lava) y [gases](https://es.wikipedia.org/wiki/Gas) provenientes del interior de la [Tierra](https://es.wikipedia.org/wiki/Tierra). El ascenso del [magma](https://es.wikipedia.org/wiki/Magma) ocurre en episodios de actividad violenta denominados [erupciones](https://es.wikipedia.org/wiki/Erupciones_volc%C3%A1nicas), que pueden variar en [intensidad](https://es.wikipedia.org/wiki/%C3%8Dndice_de_explosividad_volc%C3%A1nica), duración y frecuencia, desde suaves corrientes de lava hasta explosiones extremadamente destructivas. En ocasiones, los volcanes adquieren una forma cónica por la acumulación de material de [erupciones](https://es.wikipedia.org/wiki/Erupci%C3%B3n_volc%C3%A1nica) anteriores. En la cumbre se encuentra su [cráter](https://es.wikipedia.org/wiki/Cr%C3%A1ter_volc%C3%A1nico) o [caldera](https://es.wikipedia.org/wiki/Caldera_volc%C3%A1nica).

Por lo general los volcanes se forman en los límites de las [placas tectónicas](https://es.wikipedia.org/wiki/Tect%C3%B3nica_de_placas), aunque existen los llamados [puntos calientes](https://es.wikipedia.org/wiki/Punto_caliente_(geolog%C3%ADa)), donde no hay contacto entre placas, como es el caso de las [islas Hawái](https://es.wikipedia.org/wiki/Haw%C3%A1i).

Los volcanes pueden tener muchas formas y despedir distintos materiales. Algunas de las formas más comunes son el [estratovolcán](https://es.wikipedia.org/wiki/Estratovolc%C3%A1n), [el cono de escoria](https://es.wikipedia.org/wiki/Cono_de_escoria), [la caldera volcánica](https://es.wikipedia.org/wiki/Caldera_volc%C3%A1nica) y [el volcán en escudo](https://es.wikipedia.org/wiki/Volc%C3%A1n_en_escudo). También existen numerosos [volcanes submarinos](https://es.wikipedia.org/wiki/Volc%C3%A1n_submarino) ubicados a lo largo de las [dorsales oceánicas](https://es.wikipedia.org/wiki/Dorsal_centro-oce%C3%A1nica). Algunos volcanes alcanzan una altitud superior a los 6000 metros sobre el nivel del mar. El volcán más alto del mundo es el [Nevado Ojos del Salado](https://es.wikipedia.org/wiki/Nevado_Ojos_del_Salado), en [Argentina](https://es.wikipedia.org/wiki/Argentina) y [Chile](https://es.wikipedia.org/wiki/Chile), siendo además la segunda cumbre más alta de los hemisferios sur y occidental (solo superado por el cerro [argentino](https://es.wikipedia.org/wiki/Argentina) [Aconcagua](https://es.wikipedia.org/wiki/Aconcagua)).[3](https://es.wikipedia.org/wiki/Volc%C3%A1n#cite_note-3)​

Los volcanes no solo existen en la Tierra, sino también en otros [planetas](https://es.wikipedia.org/wiki/Planeta) y [satélites](https://es.wikipedia.org/wiki/Sat%C3%A9lite_natural). Algunos están formados por materiales considerados fríos y se denominan [criovolcanes](https://es.wikipedia.org/wiki/Criovolc%C3%A1n). En ellos, el [hielo](https://es.wikipedia.org/wiki/Hielo) actúa como [roca](https://es.wikipedia.org/wiki/Roca), mientras que el agua fría líquida interna actúa como magma; esto ocurre en la luna de [Júpiter](https://es.wikipedia.org/wiki/J%C3%BApiter_(planeta)) llamada [Europa](https://es.wikipedia.org/wiki/Europa_(sat%C3%A9lite)).
Relación entre vulcanismo y las placas tectónicas
Límites de placa divergentes
En las crestas oceánicas medias, dos placas tectónicas divergen entre sí a medida que se forma una nueva corteza oceánica por el enfriamiento y la solidificación de la roca fundida caliente. Debido a que la corteza es muy delgada en estas crestas debido al tirón de las placas tectónicas, la liberación de presión conduce a la expansión adiabática (sin transferencia de calor o materia) y al derretimiento parcial del manto, causando vulcanismo y creando una nueva corteza oceánica. La mayoría de los límites de placas divergentes se encuentran en el fondo de los océanos; por lo tanto, la mayor parte de la actividad volcánica en la Tierra es submarina, formando un nuevo fondo marino. Los fumadores negros (también conocidos como respiraderos de aguas profundas) son evidencia de este tipo de actividad volcánica. Donde la cresta oceánica media está sobre el nivel del mar, se forman islas volcánicas; por ejemplo, Islandia.

Placas convergentes
Las zonas de subducción son lugares donde chocan dos placas, generalmente una placa oceánica y una placa continental. En este caso, la placa oceánica se subduce, o se sumerge, debajo de la placa continental, formando una trinchera oceánica profunda en alta mar. En un proceso llamado fusión de flujo, el agua liberada de la placa subductora reduce la temperatura de fusión de la cuña del manto suprayacente, creando así magma. Este magma tiende a ser extremadamente viscoso debido a su alto contenido de sílice, por lo que a menudo no alcanza la superficie sino que se enfría y solidifica en profundidad. Cuando llega a la superficie, sin embargo, se forma un volcán. Ejemplos típicos son el Etna y los volcanes en el Anillo de Fuego del Pacífico.

Puntos calientes
Los puntos calientes son áreas volcánicas formadas por [plumas de manto](https://es.wikipedia.org/wiki/Pluma_mant%C3%A9lica), que son columnas de material caliente que se elevan desde el límite núcleo-manto en un espacio fijo que causa la fusión de grandes volúmenes. En algunos casos, debido a que las placas tectónicas se mueven a través de ellas, cada volcán se vuelve inactivo y se forma uno nuevo a medida que la placa avanza sobre el penacho térmico, como en el caso del [archipiélago de Hawái](https://es.wikipedia.org/wiki/Archipi%C3%A9lago_de_Haw%C3%A1i); también lo ha hecho la llanura del río Snake, con la [caldera de Yellowstone](https://es.wikipedia.org/wiki/Caldera_de_Yellowstone) como parte de la placa de América del Norte sobre el punto caliente. Otros ejemplos de vulcanismo asociado a punto caliente son las islas [Canarias](https://es.wikipedia.org/wiki/Canarias), esta vez con un desplazamiento mínimo de la placa africana, o [Islandia](https://es.wikipedia.org/wiki/Islandia), que además coincide con un límite divergente de placas.

Tipos de volcanes según su actividad
Los volcanes, teniendo en cuenta la frecuencia de sus erupciones, se pueden clasificar en tres tipos: activos, inactivos (durmientes) o extintos.

Volcanes activos
Los volcanes activos son aquellos que pueden entrar en actividad eruptiva en cualquier momento, es decir, que permanecen en estado de latencia. Esto ocurre con la mayoría de los volcanes, pues ocasionalmente entran en actividad, permaneciendo en reposo la mayor parte del tiempo. El período de actividad eruptiva puede durar desde una hora hasta varios años, como fue el caso del [volcán de Pacaya](https://es.wikipedia.org/wiki/Volc%C3%A1n_de_Pacaya) y del [Irazú](https://es.wikipedia.org/wiki/Iraz%C3%BA). A día de hoy, no se ha descubierto ningún método seguro para predecir las erupciones.

Volcanes durmientes o inactivos
Los volcanes durmientes o inactivos son aquellos que mantienen ciertos signos de actividad, como la presencia de [aguas termales](https://es.wikipedia.org/wiki/Aguas_termales), y han entrado en actividad esporádicamente. Dentro de esta categoría suelen incluirse las [fumarolas](https://es.wikipedia.org/wiki/Fumarolas) y los volcanes con largos períodos de inactividad entre una [erupción](https://es.wikipedia.org/wiki/Erupci%C3%B3n_volc%C3%A1nica) y otra. Un volcán se considera durmiente si desde hace siglos no ha tenido una erupción.

Volcanes extintos
Artículo principal: [Volcán extinto](https://es.wikipedia.org/wiki/Volc%C3%A1n_extinto)
Los [volcanes extintos](https://es.wikipedia.org/wiki/Volc%C3%A1n_extinto) son aquellos cuya última erupción fue registrada hace más de 25 000 años. Sin embargo, no se descarta la posibilidad de que puedan despertar y liberar una erupción más fuerte que la de un volcán que está activo, causando grandes desastres. También se les llama extintos cuando han sido alejados de su fuente de magma, perdiendo poco a poco su actividad, esto sucede únicamente en volcanes de punto caliente, a diferencia de los volcanes de zonas de subducción.

**Comment by Witless** [comment]
https://docs.lacabra.app/configuracion/modulos/moderacion

**Comment by holasoyender** [comment]
-- . / --.- ..- .. . .-. . -. / .- --. .. - .- .-. -- . / .. -. -.-. .. - .- -. / .- / --. .-. .. - .- .-. ... --- -.-- / -.-. --- -- --- / ..- -. .- / .-. --- -.-. .- .--. .- .-.. .- -... .-. .- ... / -. --- / -- . / - --- -.-. .- -. .- -.. . -. - .-. --- / .... .- -.-- / ..- -. / ...- --- .-.. -.-. -. --.- ..- . / .--. .-. --- -. - --- / ...- .- / .- / . ... - .- .-.. .-.. .- .-. -.-- --- / --.- ..- .. . .-. --- / . ... - .- .-. / - .-. .- -. --.- ..- .. .-.. --- . ... / -- .. / ... .. - ..- .- -.-. .. -. ..- -. .- / -.. . ... --- .-.. .- -.-. .. -. ... --- -.-- / -.-. --- -- --- / ..- -. / .-.. .- -- . -. - --- .-.. .- -- . -. - --- / -... --- .-.. .. ...- .. .- -. --- --.- ..- . / ..- -. / -.. .- / . -- .--. . --.. -.-- / -. --- / ...- .- / .- / - . .-. -- .. -. .- .-. -.-- / .- / -. .- -.. .. . / .... .- -.-. . / -.. .- --- ..- --- .... --..-- / .. --- --..-- / .. --- --..-- / .. --- ..- --- .... --- .... --..-- / -.-- . . .... . .... . .... --..-- / -.-- . .... . .... -.-- / -.-- --- / . ... - --- -.-- / .- --.- ..- -... --- .-. .-. .- -.-. .... --- / -.-- / .-.. --- -.-. --- -.-- / -- .. / -.-. --- .-. .- --.. -. / .. -.. .. --- - .- ... .. . -- .--. .-. . / -... .-. .. .-.. .-.. .- .-. / ... .. . -- .--. .-. . / -... .-. .. .-.. .-.. .- .-. -.-- / -.-- --- / - . / .- -- .- .-. - . / .- -- .- .-. / .--. --- .-. / ... .. . -- .--. .-. . -. . -. .- --..-- / -. --- / - . / .--. . .. -. . ... / . -. / .-.. .- / -.-. .- -- .- --.- ..- . / .-.. --- ... / ...- .. .- .--- .- -. - . ... / ... . / ...- .- -. / .- / .- - .-. .- ... .- .-. ..- --- .... --..-- / .. --- --..-- / .. --- --..-- / .. --- ..- --- .... --- .... --..-- / -.-- . . .... . .... . .... --..-- / -.-- . .... . .... -.-- / .... --- -.-- / . ... - --- -.-- / .- --.- ..- -... --- .-. .-. .- -.-. .... --- / -.-- / .-.. --- -.-. --- -.-- / -- .. / -.-. --- .-. .- --.. -. / .. -.. .. --- - .- ... .. . -- .--. .-. . / -... .-. .. .-.. .-.. .- .-. / ... .. . -- .--. .-. . / -... .-. .. .-.. .-.. .- .-. -.-- / -.-- --- / - . .-.-.
